### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by nmint8m** [nimblehq/ic-kmm-kayla-bruce#67]
```[tasklist]
### Tasks
- [ ] https://github.com/nimblehq/ic-kmm-kayla-bruce/issues/1
- [ ] #5
- [ ] https://github.com/nimblehq/ic-kmm-kayla-bruce/issues/6
- [ ] https://github.com/nimblehq/ic-kmm-kayla-bruce/issues/10
- [ ] #11
```
